name: chocolate-doom

on:
  push:
    paths:
      - chocolate-doom/**
      - .github/workflows/build.yml
  workflow_dispatch:

jobs:
  doom:
    uses: ./.github/workflows/build.yml
    with:
      game_dir: chocolate-doom
